// Search Results
export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS'
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS'
export const RECEIVE_CATALOGS = 'RECEIVE_CATALOGS'
export const RECEIVE_TEXTS = 'RECEIVE_TEXTS'
export const ERROR_SEARCH_RESULTS = 'ERROR_SEARCH_RESULTS'

// Term History
export const ADD_TERM_TO_HISTORY = 'ADD_TERM_TO_HISTORY'
export const SET_CURRENT_SEARCH_TERM = 'SET_CURRENT_SEARCH_TERM'

// Search Type Display
export const SET_SEARCH_TYPE_DISPLAY = 'SET_SEARCH_TYPE_DISPLAY'

// Offsets
export const SET_OFFSETS = 'SET_OFFSETS'
export const RESET_OFFSETS = 'RESET_OFFSETS'

// Favorites
export const ADD_RESULT_TO_FAVORITES = 'ADD_RESULT_TO_FAVORITES'
export const DELETE_RESULT_FROM_FAVORITES = 'DELETE_RESULT_FROM_FAVORITES'

// Selected FULL TEXT
export const SET_FULL_TEXT = 'SET_FULL_TEXT'
export const SET_FULL_TEXT_DETAILS = 'SET_FULL_TEXT_DETAILS'
export const DELETE_FULL_TEXT = 'DELETE_FULL_TEXT'
export const REQUEST_FULL_TEXT = 'REQUEST_FULL_TEXT'
export const RECEIVE_FULL_TEXT = 'RECEIVE_FULL_TEXT'
export const ERROR_FULL_TEXT = 'ERROR_FULL_TEXT'
